---
# Database credentials
apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
type: Opaque
data:
    postgres-username: cG9zdGdyZXM= # postgres encoded as base64
    postgres-password: ZXhhbXBsZQ== # example encoded as base64

---
# Database URL config map
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
data:
  database_url: postgres-service

---
# postgres server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1000m"

---
# postgres service port 5432
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
# Application port 3001
apiVersion: apps/v1
kind: Deployment
metadata:
  name: names-application
  labels:
    app: names-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: names-application
  template:
    metadata:
      labels:
        app: names-application
    spec:
      containers:
      - name: names-application
        image: gathecageorge/node-names-application:latest
        ports:
        - containerPort: 3001
        env:
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-username
        - name: DATABASE_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: DATABASE_HOST
          valueFrom: 
            configMapKeyRef:
              name: postgres-configmap
              key: database_url
        - name: APPLICATION_PORT
          value: "3001" 
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

---
# Application service 3001
apiVersion: v1
kind: Service
metadata:
  name: names-application-service
spec:
  selector:
    app: names-application
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001
