volumes:
  user-home:
  db-data:
  
services:
  node-names-application:
    build: 
      context: .
      dockerfile: Dockerfile

    volumes:
      # User home dir persist
      - user-home:/home/node

      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker-host.sock 
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../:/node-names-application

    # Overrides default command so things don't shut down after the process ends.
    entrypoint: /usr/local/share/docker-init.sh
    command: sleep infinity
    hostname: dev-container
    ports:
      - 4000:4000
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
